// Code generated by genmermaid; DO NOT EDIT.

package airplan

// MermaidVersion is the exact Mermaid release used by built-in pages.
const MermaidVersion = "11.16.0"

// DefaultMermaidURL is the exact pinned module URL used by built-in pages.
const DefaultMermaidURL = "https://cdn.jsdelivr.net/npm/mermaid@" +
	MermaidVersion + "/dist/mermaid.esm.min.mjs"
