// Command genmermaid generates the pinned Mermaid dependency constants.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"time"
)

var stableSemver = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+$`)

type manifest struct {
	Package    string `json:"package"`
	Version    string `json:"version"`
	ReleasedAt string `json:"released_at"`
}

func main() {
	check := flag.Bool("check", false, "verify output is current")
	flag.Parse()
	if flag.NArg() != 2 {
		fmt.Fprintln(os.Stderr, "usage: genmermaid [--check] MANIFEST OUTPUT")
		os.Exit(2)
	}
	if err := run(flag.Arg(0), flag.Arg(1), *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(manifestPath, outputPath string, check bool) error {
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		return err
	}
	var pin manifest
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&pin); err != nil {
		return fmt.Errorf("decode Mermaid manifest: %w", err)
	}
	if pin.Package != "mermaid" || !stableSemver.MatchString(pin.Version) {
		return fmt.Errorf("invalid stable Mermaid package/version")
	}
	released, err := time.Parse(time.RFC3339Nano, pin.ReleasedAt)
	if err != nil || released.Location() != time.UTC {
		return fmt.Errorf("released_at must be a canonical UTC timestamp")
	}
	source := fmt.Sprintf(`// Code generated by genmermaid; DO NOT EDIT.

package airplan

// MermaidVersion is the exact Mermaid release used by built-in pages.
const MermaidVersion = %q

// DefaultMermaidURL is the exact pinned module URL used by built-in pages.
const DefaultMermaidURL = "https://cdn.jsdelivr.net/npm/mermaid@" +
	MermaidVersion + "/dist/mermaid.esm.min.mjs"
`, pin.Version)
	want, err := format.Source([]byte(source))
	if err != nil {
		return err
	}
	if check {
		got, err := os.ReadFile(outputPath)
		if err != nil || !bytes.Equal(got, want) {
			return fmt.Errorf("%s is stale; run mise run generate", outputPath)
		}
		return nil
	}
	return os.WriteFile(outputPath, want, 0o644)
}
