name: GoReleaser check

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read

env:
  MISE_DISABLE_TOOLS: go

jobs:
  goreleaser-check:
    if: >-
      github.event_name == 'push' ||
      (
        contains(github.event.pull_request.labels.*.name, 'ci:goreleaser') &&
        (
          github.event.action != 'labeled' ||
          github.event.label.name == 'ci:goreleaser'
        )
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: .go-version
          cache-dependency-path: go.sum
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          add_shims_to_path: false
          cache_save: ${{ github.event_name != 'pull_request' }}
      - run: mise run release:snapshot
